### ISSUE TITLE
Shift has no effect in linux terminal

### ISSUE THREAD

**Issue by senia-psm** [lihaoyi/Ammonite#305] opened 2015-12-12 09:14 UTC
Steps to reproduce:

1) Open linux terminal (Ctrl+Alt+F1), login, run Ammonite
2) Type something
3) Press Shift+Left

Expected result: char selected.
Actual result: no reaction.

Same with Shift+Right/Up/Down

**Comment by PanAeon** [comment] 2017-05-17 10:24
works for me when I open a terminal inside X. When I open terminal via Ctrl-Alt-F1 then I'm not able to select via SHIFT not only inside ammonite, but also in bash. So I think the issue is not related to ammonite.
bash **4.4.5**
ammonite **0.8.4**

**Comment by lihaoyi** [comment] 2017-05-18 10:50
I'm going to call this a wontfix, since I don't have a linux machine to reproduce it on. Anyone who wants to fix it feel free to send a PR

**Closed by lihaoyi** 2017-05-18 10:50 UTC
Labels: bug
