### ISSUE TITLE
Bootstrap file for 2.12 starts REPL with Scala 2.13

### ISSUE THREAD

**Issue by ChernikovP** [lihaoyi/Ammonite#1059] opened 2020-04-07 13:08 UTC
Trying to install ammonite via bootstrap script , but the Scala version eventually used is not as expected (2.13.1 instead of 2.12.x): 

```
$ curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.0.4/2.12-2.0.4-bootstrap > amm && chmod +x amm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   610  100   610    0     0   1616      0 --:--:-- --:--:-- --:--:--  1618
100   924  100   924    0     0    882      0  0:00:01  0:00:01 --:--:--  902k
$ ~/amm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600  100   600    0     0   1535      0 --:--:-- --:--:-- --:--:--  1538
100 29.7M  100 29.7M    0     0  5872k      0  0:00:05  0:00:05 --:--:-- 6828k
Loading...
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/replBridge.sc
Compiling (synthetic)/ammonite/predef/sourceBridge.sc
Compiling (synthetic)/ammonite/predef/frontEndBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Welcome to the Ammonite Repl 2.0.4 (Scala 2.13.1 Java 1.8.0_161)
```

**Comment by qingwei91** [comment] 2020-04-21 08:07
@ChernikovP I submitted a PR to fix this https://github.com/lihaoyi/Ammonite/pull/1063

You can try to fix it locally by copying the corresponding change into your `amm` bootstrap file

**Comment by lihaoyi** [comment] 2020-05-12 13:16
duplicate of https://github.com/lihaoyi/Ammonite/issues/1018

**Closed by lihaoyi** 2020-05-12 13:16 UTC
