### ISSUE TITLE
$file doesn't work correctly when run from ammonite predef file

### ISSUE THREAD

**Issue by AleksanderBG** [lihaoyi/Ammonite#616] opened 2017-05-26 12:30 UTC
As in the title:
```
$ cat predef.sc
import $file.test
$ cat test.sc
val f = 5
$ coursier launch com.lihaoyi:ammonite_2.12.2:0.9.3 -- -f predef.sc
Loading...
Compiling /Users/aleksbg/amm/predef.sc
Compiling /Users/aleksbg/amm/test.sc
Welcome to the Ammonite Repl 0.9.3
(Scala 2.12.2 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ test
cmd0.sc:1: not found: value test
val res0 = test
           ^
Compilation Failed
@ $file.test
res0: $file.test.type = test
@
```

**Comment by lihaoyi** [comment] 2017-05-26 12:40
Specifically, the issue is the imports in the respective predef file are meant to be automatically propagated to the REPL/scripts, but I guess the logic around the ImportHooks in the predef isn't doing it correctly so the magic-imported `$file.test` isn't being made available in the REPL as `test`

**Comment by lihaoyi** [comment] 2017-05-26 14:20
Fixed by https://github.com/lihaoyi/Ammonite/commit/49e007dccc4c5ac7ad78f7d4f124fb436d5f053c

**Closed by lihaoyi** 2017-05-26 14:20 UTC

**Comment by lihaoyi** [comment] 2017-05-26 15:08
Fixed in the latest unstable 
```scala
lihaoyi Ammonite$ cat ~/.ammonite/predef.sc
import $file.foo
lihaoyi Ammonite$ cat ~/.ammonite/foo.sc
val bar = 1337
lihaoyi Ammonite$ amm
Loading...
Welcome to the Ammonite Repl 49e007d
(Scala 2.12.2 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ foo.bar
res0: Int = 1337
```
