### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by puffnfresh** [lihaoyi/Ammonite#490] opened 2016-10-25 09:05 UTC
```
Loading...
Welcome to the Ammonite Repl 0.7.8
(Scala 2.11.8 Java 1.8.0_73)
@ import $file 
Exception in thread "main" java.lang.NullPointerException
	at fansi.Str$.apply(Fansi.scala:304)
	at fansi.Str$.implicitApply(Fansi.scala:271)
	at ammonite.repl.Repl$.highlightFrame(Repl.scala:131)
	at ammonite.repl.Repl$$anonfun$7$$anonfun$apply$5.apply(Repl.scala:152)
	at ammonite.repl.Repl$$anonfun$7$$anonfun$apply$5.apply(Repl.scala:152)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at ammonite.repl.Repl$$anonfun$7.apply(Repl.scala:152)
	at ammonite.repl.Repl$$anonfun$7.apply(Repl.scala:147)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ammonite.repl.Repl$.showException(Repl.scala:147)
	at ammonite.repl.Repl.loop$1(Repl.scala:109)
	at ammonite.repl.Repl.run(Repl.scala:117)
	at ammonite.Main.run(Main.scala:108)
	at ammonite.Main$$anonfun$main$1$$anonfun$apply$1.apply(Main.scala:249)
	at ammonite.Main$.ammonite$Main$$ifContinually$1(Main.scala:228)
	at ammonite.Main$$anonfun$main$1.apply(Main.scala:230)
	at ammonite.Main$$anonfun$main$1.apply(Main.scala:230)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.Main$.main(Main.scala:230)
	at ammonite.Main.main(Main.scala)
```

**Comment by tkroman** [comment] 2016-10-25 09:35
This is a duplicate of #463

**Closed** 2016-10-25 09:36 UTC
