### ISSUE TITLE
Error when installing ammonite scripts

### ISSUE THREAD

**Issue by c-jonua** [lihaoyi/Ammonite#705] opened 2017-09-25 16:30 UTC
Command

```
sudo curl -L -o /usr/local/bin/amm https://git.io/v5Tct && sudo chmod +x /usr/local/bin/amm && amm
```

Log:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   600    0   600    0     0    350      0 --:--:--  0:00:01 --:--:--   350
100 37.1M  100 37.1M    0     0  2148k      0  0:00:17  0:00:17 --:--:-- 3765k
Loading...
Compiling (synthetic)/ammonite/predef/interpBridge.sc
java.lang.ExceptionInInitializerError
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:458)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:514)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:513)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:510)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:510)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:546)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:346)
  ammonite.util.Catching.flatMap(Res.scala:109)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:337)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:329)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:104)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:104)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:26)
  scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  scala.collection.immutable.List.foldLeft(List.scala:86)
  ammonite.util.Res$.fold(Res.scala:24)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:106)
  ammonite.repl.Repl.initializePredef(Repl.scala:107)
  ammonite.Main.run(Main.scala:178)
  ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:355)
  ammonite.MainRunner.watchLoop(Main.scala:336)
  ammonite.MainRunner.runRepl(Main.scala:355)
  ammonite.Main$.main0(Main.scala:277)
  ammonite.Main$.main(Main.scala:241)
  ammonite.Main.main(Main.scala)
java.lang.NullPointerException
  ammonite.runtime.Classpath$.<init>(Classpath.scala:30)
  ammonite.runtime.Classpath$.<clinit>(Classpath.scala)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:458)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:514)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:513)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:510)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:510)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:546)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:346)
  ammonite.util.Catching.flatMap(Res.scala:109)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:337)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:329)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:104)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:104)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:26)
  scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  scala.collection.immutable.List.foldLeft(List.scala:86)
  ammonite.util.Res$.fold(Res.scala:24)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:106)
  ammonite.repl.Repl.initializePredef(Repl.scala:107)
  ammonite.Main.run(Main.scala:178)
  ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:355)
  ammonite.MainRunner.watchLoop(Main.scala:336)
  ammonite.MainRunner.runRepl(Main.scala:355)
  ammonite.Main$.main0(Main.scala:277)
  ammonite.Main$.main(Main.scala:241)
  ammonite.Main.main(Main.scala)
```

System info:

**uname -a**

```
Linux localhost.localdomain 4.12.13-300.fc26.x86_64 #1 SMP Thu Sep 14 16:00:38 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**cat /etc/*-release**

```
Fedora release 26 (Twenty Six)
NAME=Fedora
VERSION="26 (Workstation Edition)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 26 (Twenty Six)
Fedora release 26 (Twenty Six)
```

**scala -version**

```
Scala code runner version 2.12.3 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
```

**java -version**

```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Comment by amarshall** [comment] 2017-10-09 04:34
I got the same error. Switching to Java 8 worked, so probably a Java 9 issue.

**Comment by jhnsmth** [comment] 2017-10-11 09:59
duplicate of #675

**Closed** 2017-10-21 12:59 UTC
