### ISSUE TITLE
Java 9 incompatibility

### ISSUE THREAD

**Issue by ilovezfs** [lihaoyi/Ammonite#710] opened 2017-10-21 18:32 UTC
The Homebrew test block fails with Java 9.
```
==> brew test ammonite-repl --verbose
==> FAILED
Testing ammonite-repl
/usr/bin/sandbox-exec -f /tmp/homebrew20171021-58767-1b1ibb2.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ammonite-repl.rb --verbose
==> /usr/local/Cellar/ammonite-repl/1.0.3/bin/amm -c 'print("hello world!")'
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Compiling (synthetic)/ammonite/predef/interpBridge.sc
java.lang.ExceptionInInitializerError
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:458)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:514)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:513)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:510)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:510)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:546)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:346)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:337)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:329)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:104)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:104)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
  scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
  scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
  scala.collection.Iterator.foreach(Iterator.scala:929)
  scala.collection.Iterator.foreach$(Iterator.scala:929)
  scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
  scala.collection.IterableLike.foreach(IterableLike.scala:71)
  scala.collection.IterableLike.foreach$(IterableLike.scala:70)
  scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
  scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
  scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
  ammonite.util.Res$.fold(Res.scala:29)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:106)
  ammonite.Main.$anonfun$instantiateInterpreter$1(Main.scala:154)
  scala.util.Either$RightProjection.flatMap(Either.scala:702)
  ammonite.Main.instantiateInterpreter(Main.scala:125)
  ammonite.Main.runCode(Main.scala:223)
  ammonite.MainRunner.$anonfun$runCode$2(Main.scala:361)
  ammonite.MainRunner.watchLoop(Main.scala:344)
  ammonite.MainRunner.runCode(Main.scala:361)
  ammonite.Main$.main0(Main.scala:276)
  ammonite.Main$.main(Main.scala:244)
  ammonite.Main.main(Main.scala)
java.lang.NullPointerException
  ammonite.runtime.Classpath$.<init>(Classpath.scala:30)
  ammonite.runtime.Classpath$.<clinit>(Classpath.scala)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:458)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:514)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:513)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:510)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:510)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:546)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:346)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:337)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:329)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:104)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:104)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
  scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
  scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
  scala.collection.Iterator.foreach(Iterator.scala:929)
  scala.collection.Iterator.foreach$(Iterator.scala:929)
  scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
  scala.collection.IterableLike.foreach(IterableLike.scala:71)
  scala.collection.IterableLike.foreach$(IterableLike.scala:70)
  scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
  scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
  scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
  ammonite.util.Res$.fold(Res.scala:29)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:106)
  ammonite.Main.$anonfun$instantiateInterpreter$1(Main.scala:154)
  scala.util.Either$RightProjection.flatMap(Either.scala:702)
  ammonite.Main.instantiateInterpreter(Main.scala:125)
  ammonite.Main.runCode(Main.scala:223)
  ammonite.MainRunner.$anonfun$runCode$2(Main.scala:361)
  ammonite.MainRunner.watchLoop(Main.scala:344)
  ammonite.MainRunner.runCode(Main.scala:361)
  ammonite.Main$.main0(Main.scala:276)
  ammonite.Main$.main(Main.scala:244)
  ammonite.Main.main(Main.scala)
Error: ammonite-repl: failed
<0> expected but was
<1>.
```

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/11348/version=high_sierra/console

**Comment by jhnsmth** [comment] 2017-10-22 18:49
duplicate of #675

**Closed** 2017-10-22 19:26 UTC
