### ISSUE TITLE
Alt+Left/Right inserts character

### ISSUE THREAD

**Issue by senia-psm** [lihaoyi/Ammonite#304] opened 2015-12-11 15:23 UTC
Alt+Left/Right as well as Alt+Shift+Left/Right inserts character instead of moving forward/backwards by one word at a time.

Workaround with Ctrl+Left/Right works.
Workaround with Ctrl+Shift+Left/Right inserts character instead of selecting text.

According to error message on Alt+Left/Right, Enter:

``` scala
SyntaxError: found "\u001b[1;3D", expected TopPkgSeq | Import | Prelude ~ BlockDef | Expr | End at index 0
```

Environment 1: Cygwin terminal + ssh + screen.
`Alt+Left` - "\u001b[1;3D"
`Alt+Right` - "\u001b[1;3C"
`Alt+Shift+Left` - "\u001b[1;4D"
`Alt+Shift+Right` - "\u001b[1;4C"
`Ctrl+Shift+Left` - "\u001b[1;6D"
`Ctrl+Shift+Right` - "\u001b[1;6C"

Environment 2: Konsole (KDE) with or without screen.
`Alt+Left` - "\u001b[1;3D"
`Alt+Right` - "\u001b[1;3C"
`Alt+Shift+Left` - no reaction
`Alt+Shift+Right` - no reaction
`Ctrl+Shift+Left` - no reaction
`Ctrl+Shift+Right` - no reaction

Additional information:

``` bash
$ uname -rio
4.1.12-gentoo GenuineIntel GNU/Linux
```

**Comment by lihaoyi** [comment] 2017-05-18 10:51
I'm going to call this a wontfix, since I don't have a linux machine to reproduce it on. Anyone who wants to fix it feel free to send a PR

**Closed by lihaoyi** 2017-05-18 10:51 UTC
Labels: bug
