### ISSUE TITLE
Ammonite swallows compiler warnings

### ISSUE THREAD

**Issue by ryan-richt** [lihaoyi/Ammonite#331] opened 2016-01-27 18:28 UTC
Maybe there is a way I can't find in the docs to configure this (otherwise so excited about Ammonite!) but ...
Compared to the Scala REPL, compiler warnings are not printed in line (or at all). For instance:

List(1) match {
  case _:List[Double] => 2
  }
res61: Int = 2

should indicate:

<console>:12: warning: fruitless type test: a value of type List[Int] cannot also be a List[Double] (the underlying of List[Double]) (but still might match its erasure)
         case _:List[Double] => 2

**Comment by lihaoyi** [comment] 2016-01-27 18:31
Closing as duplicate of https://github.com/lihaoyi/Ammonite/issues/296

**Closed by lihaoyi** 2016-01-27 18:31 UTC
