### ISSUE TITLE
Ammonite's dependencies conflict with others on classpath

### ISSUE THREAD

**Issue by bblfish** [lihaoyi/Ammonite#292] opened 2015-12-08 17:03 UTC
I was trying to run code [from my branch of upickle](https://github.com/bblfish/upickle-pprint/commit/597ba2573228293f02dbf70ac64a2ac79197bf07) [related to issue 122](https://github.com/lihaoyi/upickle-pprint/pull/122) using Ammonite started from sbt from  inside the `upickleJVM` project. 

I tried what the docs suggested to place in `global.sbt` and the following

```
libraryDependencies += "com.lihaoyi" % "ammonite-repl" % "0.5.1" cross CrossVersion.full

initialCommands in (console) := """ammonite.repl.Main.run("")"""
```

I I then run `compile:console` and end up in the **amm** console.

But it looks like I cannot create a `Js.Unserializable("hi")` there. The class is not found even though it is in the code.

But when  I `^D` from amm back to the  normal scala console started by sbt, I can create an instance of `Js.Unserializable`

**Comment by lihaoyi** [comment] 2015-12-10 10:10
The basic problem here is that we have no isolation between Ammonite and the stuff we run inside it. That means basically anything in this list

https://github.com/lihaoyi/Ammonite/blob/master/build.sbt#L107-L115

Will have some kind of weird mis-behavior if you try to develop using Ammonite, or even if you're just using a different version of that library in the same project. Possible solutions include:

- JarJar https://github.com/Tapad/sbt-jarjar, which IIRC does automatic-vendoring
- Classloader isolation

**Comment by fommil** [comment] 2015-12-19 18:37
oh, don't you set the `usejavacp=false` flag? e.g. https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/core/Analyzer.scala#L66

**Comment by lihaoyi** [comment] 2015-12-19 18:50
Yeah I do, and then I walk the classpath myself and gather up the jars anyway =P

**Comment by fommil** [comment] 2015-12-19 18:57
ah, right, so you're intentionally adding ammonite onto the user's classpath. I see.

**Comment by lihaoyi** [comment] 2015-12-20 06:03
Yeah, well, that's not the problem. The problem is that I want to add the *user's* classpath to *Ammonite's*. After all, I want to interact with it in the REPL! However, Ammonite has its own dependencies, and when it conflicts with the user's it's a pain. Hence the possible solutions above

**Comment by lihaoyi** [comment] 2017-06-03 13:24
Since nobody else has complained about this I'm going to close this for now

**Closed by lihaoyi** 2017-06-03 13:24 UTC
Labels: enhancement
