### ISSUE TITLE
Ammonite repl gives missing configuration error with akka

### ISSUE THREAD

**Issue by pamu** [lihaoyi/Ammonite#495] opened 2016-11-01 18:50 UTC
Ammonite repl gives missing configuration exception with akka

Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka'

**Comment by lihaoyi** [comment] 2016-11-08 11:07
Seems like a duplicate of https://github.com/lihaoyi/Ammonite/issues/496 maybe

**Closed by lihaoyi** 2016-11-08 11:07 UTC
