### ISSUE TITLE
[BUG] `import $file` uses pwd instead of wd

### ISSUE THREAD

**Issue by NightMachinary** [lihaoyi/Ammonite#785] opened 2018-03-27 14:27 UTC
`import $file` uses pwd instead of wd:
![image](https://user-images.githubusercontent.com/36224762/37973869-bbb8b04c-31f0-11e8-9304-57c4ccc63e4e.png)

**Comment by lihaoyi** [comment] 2018-03-27 15:37
duplicate of https://github.com/lihaoyi/Ammonite/issues/447

**Closed by lihaoyi** 2018-03-27 15:37 UTC
