### ISSUE TITLE
Imports getting confused with aliases

### ISSUE THREAD

**Issue by alexarchambault** [lihaoyi/Ammonite#334] opened 2016-01-30 15:11 UTC
```scala
Welcome to the Ammonite Repl 0.5.2
(Scala 2.11.7 Java 1.8.0_60)
@ import java.{io => jio}
import java.{io => jio}
@ import jio.File
import jio.File
@ new File("/tmp")
Compilation Failed
Main.scala:34: object jio is not a member of package java
import java.jio.File
            ^
Main.scala:38: not found: type File
new File("/tmp")
    ^
```

This was first reported to jupyter-scala (https://github.com/alexarchambault/jupyter-scala/issues/49).

**Comment by lihaoyi** [comment] 2016-01-30 15:52
Duplicate of https://github.com/lihaoyi/Ammonite/issues/248, let's keep discussion there

**Comment by lihaoyi** [comment] 2016-01-30 15:53
Actually it isn't

**Comment by lihaoyi** [comment] 2016-01-30 23:50
actually it is...

**Closed by lihaoyi** 2016-01-30 23:50 UTC
