### ISSUE TITLE
Ammonite REPL embedded in SBT should not alter how tests are run

### ISSUE THREAD

**Issue by HaydenSikh** [lihaoyi/Ammonite#680] opened 2017-08-10 17:29 UTC
Currently the instructions for using Ammonite with SBT instructs the user to add Ammonite to the `libraryDependencies` scoped to the test configuration.  Since this changes the test environment it can alter how tests are run, possibly introducing false positives such as the failures due to https://github.com/lihaoyi/Ammonite/issues/644, but possibly also introducing false positives where code that will fail in production can pass tests.

Would it be better to have the user create a new custom SBT configuration that extends the test configuration and only depend on Ammonite in that config?

Maybe the Ammonite dependency for SBT could be just a very thin front-end and the internal dependencies are resolved internally instead of through SBT's dependency management?

If SBT keeps the dependencies of it's plugins separate from the dependencies used for configurations, maybe this is additional rationale to pursue https://github.com/lihaoyi/Ammonite/issues/24.

**Comment by alexarchambault** [comment] 2017-08-10 18:23
That's roughly what [sbt-ammonite](https://github.com/alexarchambault/sbt-ammonite) does. I don't use it much (I tend to use in-browser notebooks now...), so I tend to only update it when I receive PRs. There was [some](https://github.com/lihaoyi/Ammonite/pull/32) [discussion](https://github.com/lihaoyi/Ammonite/pull/184) to add it to the repo of Ammonite.

**Comment by lihaoyi** [comment] 2017-08-10 23:17
Duplicate of https://github.com/lihaoyi/Ammonite/issues/24

**Closed by lihaoyi** 2017-08-10 23:17 UTC
