### ISSUE TITLE
Ammonite REPL - Undo Redo not working 

### ISSUE THREAD

**Issue by kevroger23** [lihaoyi/Ammonite#536] opened 2016-12-23 20:21 UTC
I am running   _Ammonite Repl 0.8.1_
(Scala 2.12.1 Java 1.8.0_111) on **Linux**

1) It seems Undo and Redo are not working. I tried **"Ctrl -"** and **"Alt/Esc -"** but 
it does nothing. 

2) Also  **Alt-Left/Right** to move forward/backwards **does not seem to work**. However
**Ctrl-Left/Right** seems to work **instead**.

**Are the bindings different for Linux ?**

**Comment by lihaoyi** [comment] 2017-01-01 13:35
Duplicate of #528

**Closed by lihaoyi** 2017-01-01 13:35 UTC
